name: flame_riverpod
description: Widgets, providers, and an example project for using Riverpod in conjunction with Flame.
version: 1.1.0
homepage: https://markvideon.dev

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flame: ^1.5.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0